-- Private company rosters, member avatars, and company guestbooks.
-- Run this file once in Supabase SQL Editor after the earlier migrations.

alter table public.member_records
    drop constraint if exists attendance_not_above_total;

alter table public.member_records
    drop column if exists attendance_count;

alter table public.member_records
    add column if not exists avatar_path text;

create table if not exists public.company_messages (
    id bigint generated by default as identity primary key,
    author_id uuid not null references public.profiles(id) on delete cascade,
    company text not null check (char_length(btrim(company)) between 1 and 80),
    message text not null check (char_length(btrim(message)) between 1 and 500),
    created_at timestamptz not null default now()
);

create index if not exists company_messages_company_created_idx
    on public.company_messages (company, created_at desc);

alter table public.company_messages enable row level security;

-- Return only roster-safe fields. QQ numbers, points, and private account data
-- remain unavailable to ordinary members.
create or replace function public.get_company_roster()
returns table (
    profile_id uuid,
    nickname text,
    member_role text,
    company text,
    current_rank text,
    member_status text,
    achievements text[],
    avatar_path text
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
    if auth.uid() is null or not public.is_approved_member() then
        raise exception 'Only approved members can view the roster' using errcode = '42501';
    end if;
    return query
    select p.id, p.nickname, p.role, m.company, m.current_rank,
           m.member_status, m.achievements, m.avatar_path
    from public.profiles p
    join public.member_records m on m.profile_id = p.id
    where p.account_status = 'approved';
end;
$$;

revoke all on function public.get_company_roster() from public, anon;
grant execute on function public.get_company_roster() to authenticated;

drop policy if exists "approved members read company messages" on public.company_messages;
create policy "approved members read company messages" on public.company_messages
    for select to authenticated
    using (public.is_approved_member());

drop policy if exists "approved members create company messages" on public.company_messages;
create policy "approved members create company messages" on public.company_messages
    for insert to authenticated
    with check (public.is_approved_member() and author_id = auth.uid());

drop policy if exists "admins delete company messages" on public.company_messages;
create policy "admins delete company messages" on public.company_messages
    for delete to authenticated
    using (public.is_admin());

revoke all on public.company_messages from anon;
grant select, insert, delete on public.company_messages to authenticated;
grant usage, select on sequence public.company_messages_id_seq to authenticated;

-- Members update only their own avatar path through this narrowly scoped RPC.
create or replace function public.set_own_avatar_path(p_avatar_path text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    if auth.uid() is null or not public.is_approved_member() then
        raise exception 'Only approved members can set an avatar' using errcode = '42501';
    end if;
    if p_avatar_path is null
       or p_avatar_path !~ ('^' || auth.uid()::text || '/avatar[.](jpg|jpeg|png|webp)$') then
        raise exception 'Invalid avatar path' using errcode = '22023';
    end if;
    update public.member_records
    set avatar_path = p_avatar_path
    where profile_id = auth.uid();
end;
$$;

revoke all on function public.set_own_avatar_path(text) from public, anon;
grant execute on function public.set_own_avatar_path(text) to authenticated;

-- Avatars remain private and are delivered with short-lived signed URLs.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
    'member-avatars',
    'member-avatars',
    false,
    2097152,
    array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
    public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "approved members read member avatars" on storage.objects;
create policy "approved members read member avatars" on storage.objects
    for select to authenticated
    using (bucket_id = 'member-avatars' and public.is_approved_member());

drop policy if exists "members upload own avatar" on storage.objects;
create policy "members upload own avatar" on storage.objects
    for insert to authenticated
    with check (
        bucket_id = 'member-avatars'
        and public.is_approved_member()
        and (storage.foldername(name))[1] = auth.uid()::text
    );

drop policy if exists "members replace own avatar" on storage.objects;
create policy "members replace own avatar" on storage.objects
    for update to authenticated
    using (
        bucket_id = 'member-avatars'
        and public.is_approved_member()
        and (storage.foldername(name))[1] = auth.uid()::text
    )
    with check (
        bucket_id = 'member-avatars'
        and public.is_approved_member()
        and (storage.foldername(name))[1] = auth.uid()::text
    );

drop policy if exists "members delete own avatar" on storage.objects;
create policy "members delete own avatar" on storage.objects
    for delete to authenticated
    using (
        bucket_id = 'member-avatars'
        and public.is_approved_member()
        and (storage.foldername(name))[1] = auth.uid()::text
    );
