-- War of Right Community member accounts
-- Run this entire file once in Supabase SQL Editor.

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    qq_number text not null unique check (qq_number ~ '^[0-9]{5,12}$'),
    nickname text not null check (char_length(nickname) between 2 and 24),
    account_status text not null default 'pending'
        check (account_status in ('pending', 'approved', 'rejected', 'suspended')),
    role text not null default 'member'
        check (role in ('member', 'admin', 'super_admin')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    approved_at timestamptz,
    approved_by uuid references public.profiles(id) on delete set null
);

create unique index if not exists profiles_nickname_unique_ci
    on public.profiles (lower(btrim(nickname)));

create table if not exists public.member_records (
    profile_id uuid primary key references public.profiles(id) on delete cascade,
    company text not null default '',
    current_rank text not null default '',
    promotion_path text not null default '',
    joined_on date,
    member_status text not null default '现役',
    attendance_count integer not null default 0 check (attendance_count >= 0),
    activity_total integer not null default 0 check (activity_total >= 0),
    experience_points integer not null default 0 check (experience_points >= 0),
    training_points integer not null default 0 check (training_points >= 0),
    command_points integer not null default 0 check (command_points >= 0),
    service_points integer not null default 0 check (service_points >= 0),
    achievements text[] not null default '{}',
    updated_at timestamptz not null default now(),
    constraint attendance_not_above_total check (attendance_count <= activity_total)
);

create table if not exists public.admin_notes (
    id bigint generated by default as identity primary key,
    profile_id uuid not null references public.profiles(id) on delete cascade,
    note text not null check (char_length(note) between 1 and 2000),
    created_by uuid not null references public.profiles(id) on delete restrict,
    created_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
    id bigint generated by default as identity primary key,
    actor_id uuid references public.profiles(id) on delete set null,
    target_id uuid references public.profiles(id) on delete set null,
    action text not null,
    before_data jsonb,
    after_data jsonb,
    created_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1 from public.profiles
        where id = auth.uid()
          and account_status = 'approved'
          and role in ('admin', 'super_admin')
    );
$$;

create or replace function public.is_super_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1 from public.profiles
        where id = auth.uid()
          and account_status = 'approved'
          and role = 'super_admin'
    );
$$;

create or replace function public.is_approved_member()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1 from public.profiles
        where id = auth.uid()
          and account_status = 'approved'
    );
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    new_qq text := new.raw_user_meta_data ->> 'qq_number';
    new_nickname text := btrim(new.raw_user_meta_data ->> 'nickname');
begin
    if new_qq is null or new_qq !~ '^[0-9]{5,12}$' then
        raise exception 'Invalid QQ number';
    end if;
    if new_nickname is null or char_length(new_nickname) not between 2 and 24 then
        raise exception 'Invalid nickname';
    end if;

    insert into public.profiles (id, qq_number, nickname)
    values (new.id, new_qq, new_nickname);
    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
    after insert on auth.users
    for each row execute function public.handle_new_user();

create or replace function public.protect_profile_update()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    if new.id <> old.id or new.qq_number <> old.qq_number or new.created_at <> old.created_at then
        raise exception 'Identity fields cannot be changed';
    end if;

    if new.role <> old.role and auth.uid() is not null and not public.is_super_admin() then
        raise exception 'Only a super administrator can change roles';
    end if;

    if old.role in ('admin', 'super_admin')
       and auth.uid() is not null
       and auth.uid() <> old.id
       and not public.is_super_admin() then
        raise exception 'Only a super administrator can modify another administrator';
    end if;

    if new.account_status <> old.account_status then
        if auth.uid() is not null and not public.is_admin() then
            raise exception 'Only an administrator can change account status';
        end if;
        if new.account_status = 'approved' then
            new.approved_at := now();
            new.approved_by := auth.uid();
        else
            new.approved_at := null;
            new.approved_by := null;
        end if;
    end if;

    new.updated_at := now();
    return new;
end;
$$;

drop trigger if exists protect_profile_update on public.profiles;
create trigger protect_profile_update
    before update on public.profiles
    for each row execute function public.protect_profile_update();

create or replace function public.touch_member_record()
returns trigger
language plpgsql
as $$
begin
    new.updated_at := now();
    return new;
end;
$$;

drop trigger if exists touch_member_record on public.member_records;
create trigger touch_member_record
    before update on public.member_records
    for each row execute function public.touch_member_record();

create or replace function public.audit_profile_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.audit_logs (actor_id, target_id, action, before_data, after_data)
    values (auth.uid(), new.id, 'profile.updated', to_jsonb(old), to_jsonb(new));
    return new;
end;
$$;

drop trigger if exists audit_profile_change on public.profiles;
create trigger audit_profile_change
    after update on public.profiles
    for each row execute function public.audit_profile_change();

-- Approving a member also confirms the synthetic QQ login identity. This keeps
-- pending applicants unable to sign in even when email confirmation is enabled.
create or replace function public.confirm_approved_user()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
begin
    if new.account_status = 'approved' and old.account_status <> 'approved' then
        update auth.users
        set email_confirmed_at = coalesce(email_confirmed_at, now()),
            updated_at = now()
        where id = new.id;
    end if;
    return new;
end;
$$;

drop trigger if exists confirm_approved_user on public.profiles;
create trigger confirm_approved_user
    after update of account_status on public.profiles
    for each row execute function public.confirm_approved_user();

create or replace function public.audit_member_record_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.audit_logs (actor_id, target_id, action, before_data, after_data)
    values (
        auth.uid(),
        coalesce(new.profile_id, old.profile_id),
        case when tg_op = 'INSERT' then 'member_record.created' else 'member_record.updated' end,
        case when tg_op = 'INSERT' then null else to_jsonb(old) end,
        to_jsonb(new)
    );
    return new;
end;
$$;

drop trigger if exists audit_member_record_change on public.member_records;
create trigger audit_member_record_change
    after insert or update on public.member_records
    for each row execute function public.audit_member_record_change();

alter table public.profiles enable row level security;
alter table public.member_records enable row level security;
alter table public.admin_notes enable row level security;
alter table public.audit_logs enable row level security;

drop policy if exists "read own profile or admin" on public.profiles;
create policy "read own profile or admin" on public.profiles
    for select to authenticated
    using (id = auth.uid() or public.is_admin());

drop policy if exists "admins update profiles" on public.profiles;
create policy "admins update profiles" on public.profiles
    for update to authenticated
    using (public.is_admin())
    with check (public.is_admin());

drop policy if exists "read own member record or admin" on public.member_records;
create policy "read own member record or admin" on public.member_records
    for select to authenticated
    using ((profile_id = auth.uid() and public.is_approved_member()) or public.is_admin());

drop policy if exists "admins insert member records" on public.member_records;
create policy "admins insert member records" on public.member_records
    for insert to authenticated
    with check (public.is_admin());

drop policy if exists "admins update member records" on public.member_records;
create policy "admins update member records" on public.member_records
    for update to authenticated
    using (public.is_admin())
    with check (public.is_admin());

drop policy if exists "admins delete member records" on public.member_records;
create policy "admins delete member records" on public.member_records
    for delete to authenticated
    using (public.is_admin());

drop policy if exists "admins manage notes" on public.admin_notes;
create policy "admins manage notes" on public.admin_notes
    for all to authenticated
    using (public.is_admin())
    with check (public.is_admin() and created_by = auth.uid());

drop policy if exists "admins read audit logs" on public.audit_logs;
create policy "admins read audit logs" on public.audit_logs
    for select to authenticated
    using (public.is_admin());

revoke all on public.profiles, public.member_records, public.admin_notes, public.audit_logs from anon;
grant select, update on public.profiles to authenticated;
grant select, insert, update, delete on public.member_records to authenticated;
grant select, insert, update, delete on public.admin_notes to authenticated;
grant select on public.audit_logs to authenticated;
grant usage, select on sequence public.admin_notes_id_seq to authenticated;

-- After registering your own account, run the following separately with your QQ number:
-- update public.profiles
-- set account_status = 'approved', role = 'super_admin', approved_at = now()
-- where qq_number = 'YOUR_QQ_NUMBER';
