-- Lightweight public forum for the 2nd Virginia Cavalry community.
-- Run this entire file once in Supabase SQL Editor.

create table if not exists public.forum_posts (
    id bigint generated by default as identity primary key,
    author_id uuid not null references public.profiles(id) on delete cascade,
    category text not null check (category in ('announcements', 'events', 'tactics', 'chat')),
    title text not null check (char_length(btrim(title)) between 2 and 80),
    body text not null check (char_length(btrim(body)) between 1 and 4000),
    is_pinned boolean not null default false,
    is_locked boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.forum_comments (
    id bigint generated by default as identity primary key,
    post_id bigint not null references public.forum_posts(id) on delete cascade,
    author_id uuid not null references public.profiles(id) on delete cascade,
    body text not null check (char_length(btrim(body)) between 1 and 2000),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.forum_reports (
    id bigint generated by default as identity primary key,
    reporter_id uuid not null references public.profiles(id) on delete cascade,
    post_id bigint references public.forum_posts(id) on delete cascade,
    comment_id bigint references public.forum_comments(id) on delete cascade,
    reason text not null check (char_length(btrim(reason)) between 2 and 500),
    created_at timestamptz not null default now(),
    constraint forum_reports_one_target check ((post_id is not null) <> (comment_id is not null))
);

create index if not exists forum_posts_feed_idx
    on public.forum_posts (is_pinned desc, created_at desc);
create index if not exists forum_posts_category_feed_idx
    on public.forum_posts (category, is_pinned desc, created_at desc);
create index if not exists forum_comments_post_idx
    on public.forum_comments (post_id, created_at);
create unique index if not exists forum_reports_post_once_idx
    on public.forum_reports (reporter_id, post_id) where post_id is not null;
create unique index if not exists forum_reports_comment_once_idx
    on public.forum_reports (reporter_id, comment_id) where comment_id is not null;

alter table public.forum_posts enable row level security;
alter table public.forum_comments enable row level security;
alter table public.forum_reports enable row level security;

drop policy if exists "public reads forum posts" on public.forum_posts;
create policy "public reads forum posts" on public.forum_posts
    for select to anon, authenticated using (true);

drop policy if exists "approved members create forum posts" on public.forum_posts;
create policy "approved members create forum posts" on public.forum_posts
    for insert to authenticated
    with check (
        public.is_approved_member()
        and author_id = auth.uid()
        and not is_pinned
        and not is_locked
    );

drop policy if exists "admins moderate forum posts" on public.forum_posts;
create policy "admins moderate forum posts" on public.forum_posts
    for update to authenticated
    using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admins delete forum posts" on public.forum_posts;
create policy "admins delete forum posts" on public.forum_posts
    for delete to authenticated using (public.is_admin());

drop policy if exists "public reads forum comments" on public.forum_comments;
create policy "public reads forum comments" on public.forum_comments
    for select to anon, authenticated using (true);

drop policy if exists "approved members create forum comments" on public.forum_comments;
create policy "approved members create forum comments" on public.forum_comments
    for insert to authenticated
    with check (
        public.is_approved_member()
        and author_id = auth.uid()
        and exists (select 1 from public.forum_posts p where p.id = post_id and not p.is_locked)
    );

drop policy if exists "members or admins delete forum comments" on public.forum_comments;
create policy "members or admins delete forum comments" on public.forum_comments
    for delete to authenticated
    using (author_id = auth.uid() or public.is_admin());

drop policy if exists "approved members create forum reports" on public.forum_reports;
create policy "approved members create forum reports" on public.forum_reports
    for insert to authenticated
    with check (public.is_approved_member() and reporter_id = auth.uid());

drop policy if exists "admins read forum reports" on public.forum_reports;
create policy "admins read forum reports" on public.forum_reports
    for select to authenticated using (public.is_admin());

drop policy if exists "admins resolve forum reports" on public.forum_reports;
create policy "admins resolve forum reports" on public.forum_reports
    for delete to authenticated using (public.is_admin());

create or replace function public.forum_post_rate_limit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    if exists (
        select 1 from public.forum_posts
        where author_id = new.author_id and created_at > now() - interval '30 seconds'
    ) then
        raise exception 'Please wait before creating another post' using errcode = 'P0001';
    end if;
    new.title := btrim(new.title);
    new.body := btrim(new.body);
    return new;
end;
$$;

create or replace function public.forum_comment_rate_limit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    if exists (
        select 1 from public.forum_comments
        where author_id = new.author_id and created_at > now() - interval '10 seconds'
    ) then
        raise exception 'Please wait before commenting again' using errcode = 'P0001';
    end if;
    new.body := btrim(new.body);
    return new;
end;
$$;

drop trigger if exists forum_post_rate_limit_trigger on public.forum_posts;
create trigger forum_post_rate_limit_trigger
    before insert on public.forum_posts
    for each row execute function public.forum_post_rate_limit();

drop trigger if exists forum_comment_rate_limit_trigger on public.forum_comments;
create trigger forum_comment_rate_limit_trigger
    before insert on public.forum_comments
    for each row execute function public.forum_comment_rate_limit();

create or replace function public.get_forum_posts(
    p_category text default null,
    p_offset integer default 0,
    p_limit integer default 20
)
returns table (
    id bigint,
    category text,
    title text,
    body text,
    is_pinned boolean,
    is_locked boolean,
    created_at timestamptz,
    updated_at timestamptz,
    nickname text,
    current_rank text,
    avatar_path text,
    comment_count bigint
)
language sql
stable
security definer
set search_path = public
as $$
    select fp.id, fp.category, fp.title, fp.body, fp.is_pinned, fp.is_locked,
           fp.created_at, fp.updated_at, pr.nickname, mr.current_rank,
           case when public.is_approved_member() then mr.avatar_path else null end,
           (select count(*) from public.forum_comments fc where fc.post_id = fp.id)
    from public.forum_posts fp
    join public.profiles pr on pr.id = fp.author_id
    left join public.member_records mr on mr.profile_id = fp.author_id
    where p_category is null or fp.category = p_category
    order by fp.is_pinned desc, fp.created_at desc
    offset greatest(coalesce(p_offset, 0), 0)
    limit least(greatest(coalesce(p_limit, 20), 1), 50);
$$;

create or replace function public.get_forum_comments(p_post_id bigint)
returns table (
    id bigint,
    post_id bigint,
    body text,
    created_at timestamptz,
    nickname text,
    current_rank text,
    avatar_path text,
    viewer_owns boolean
)
language sql
stable
security definer
set search_path = public
as $$
    select fc.id, fc.post_id, fc.body, fc.created_at, pr.nickname, mr.current_rank,
           case when public.is_approved_member() then mr.avatar_path else null end,
           fc.author_id = auth.uid()
    from public.forum_comments fc
    join public.profiles pr on pr.id = fc.author_id
    left join public.member_records mr on mr.profile_id = fc.author_id
    where fc.post_id = p_post_id
    order by fc.created_at;
$$;

create or replace function public.get_forum_reports()
returns table (
    id bigint,
    post_id bigint,
    comment_id bigint,
    reason text,
    created_at timestamptz,
    reporter_nickname text,
    target_excerpt text
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
    if not public.is_admin() then
        raise exception 'Administrator access required' using errcode = '42501';
    end if;
    return query
    select fr.id, fr.post_id, fr.comment_id, fr.reason, fr.created_at,
           pr.nickname,
           left(coalesce(fp.title, fc.body, ''), 100)
    from public.forum_reports fr
    join public.profiles pr on pr.id = fr.reporter_id
    left join public.forum_posts fp on fp.id = fr.post_id
    left join public.forum_comments fc on fc.id = fr.comment_id
    order by fr.created_at desc;
end;
$$;

revoke all on public.forum_posts, public.forum_comments, public.forum_reports from anon, authenticated;
grant select on public.forum_posts, public.forum_comments to anon, authenticated;
grant insert on public.forum_posts, public.forum_comments to authenticated;
grant update, delete on public.forum_posts to authenticated;
grant delete on public.forum_comments to authenticated;
grant select, insert, delete on public.forum_reports to authenticated;
grant usage, select on sequence public.forum_posts_id_seq, public.forum_comments_id_seq, public.forum_reports_id_seq to authenticated;

revoke all on function public.get_forum_posts(text, integer, integer) from public;
grant execute on function public.get_forum_posts(text, integer, integer) to anon, authenticated;
revoke all on function public.get_forum_comments(bigint) from public;
grant execute on function public.get_forum_comments(bigint) to anon, authenticated;
revoke all on function public.get_forum_reports() from public, anon;
grant execute on function public.get_forum_reports() to authenticated;
